on:
  push:
    branches:
      - master
name: Release
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, Build & Pack
        run: |
          npm i
          npm run build
          cd dist
          npm pack

      - name: Push To Release
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "dist/dismissible-1.0.0.tgz"
          token: ${{ secrets.token }}
          tag: v1.0.0